CREATE DATABASE IF NOT EXISTS furryfriends;
USE furryfriends;

CREATE TABLE IF NOT EXISTS Users (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    Username VARCHAR(40) NOT NULL UNIQUE,
    Password VARCHAR(100) NOT NULL,
    Name VARCHAR(50) NOT NULL,
    Phone VARCHAR(50) NOT NULL,
    Email VARCHAR(50) NOT NULL UNIQUE,
    Role TINYINT(1) NOT NULL,
    Status TINYINT(1) NOT NULL
);

CREATE TABLE IF NOT EXISTS Categories (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL UNIQUE,
    Image VARCHAR(255) NOT NULL,
    Status TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS Products (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Discount DECIMAL(10,2) NOT NULL DEFAULT 0.00,
    Image VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    Detail TEXT NOT NULL,
    Quantity INT(11) NOT NULL DEFAULT 0,
    Status TINYINT(1) NOT NULL DEFAULT 1,
    Views INT(11) NOT NULL DEFAULT 0,
    Category_ID INT(11) NOT NULL,
    FOREIGN KEY (Category_ID) REFERENCES Categories(ID)
);

CREATE TABLE IF NOT EXISTS Services (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(100) NOT NULL,
    Price DECIMAL(10,2) NOT NULL,
    Detail TEXT NOT NULL,
    Time_Service TIME NOT NULL,
    Category_ID INT(11) NOT NULL,
    FOREIGN KEY (Category_ID) REFERENCES Categories(ID)
);

CREATE TABLE IF NOT EXISTS Service_Comments (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    ID_User INT(11) NOT NULL,
    ID_Service INT(11) NOT NULL,
    Date DATETIME NOT NULL,
    Status TINYINT(1) NOT NULL DEFAULT 1,
    Comment TEXT NOT NULL,
    FOREIGN KEY (ID_User) REFERENCES Users(ID),
    FOREIGN KEY (ID_Service) REFERENCES Services(ID)
);

CREATE TABLE IF NOT EXISTS Rating_Product (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    ID_User INT(11) NOT NULL,
    ID_Product INT(11) NOT NULL,
    Date DATETIME NOT NULL,
    Status TINYINT(1) NOT NULL DEFAULT 0,
    Rating TINYINT(1) NOT NULL,
    Review TEXT NOT NULL,
    FOREIGN KEY (ID_User) REFERENCES Users(ID),
    FOREIGN KEY (ID_Product) REFERENCES Products(ID)
);

CREATE TABLE IF NOT EXISTS Orders (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    ID_User INT(11) NOT NULL,
    Name VARCHAR(100) NOT NULL,
    Phone VARCHAR(50) NOT NULL,
    Address TEXT NOT NULL,
    Create_Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Payment_Method TINYINT(1) NOT NULL DEFAULT 0,
    Total DECIMAL(10,2) NOT NULL,
    Payment_Date DATETIME,
    Status_Order TINYINT(1) NOT NULL DEFAULT 0,
    FOREIGN KEY (ID_User) REFERENCES Users(ID)
);

CREATE TABLE IF NOT EXISTS Order_Details (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    ID_Order INT(11) NOT NULL,
    ID_Product INT(11) NULL,
    Price DECIMAL(10,2) NOT NULL,
    Quantity INT(11) NOT NULL,
    FOREIGN KEY (ID_Order) REFERENCES Orders(ID),
    FOREIGN KEY (ID_Product) REFERENCES Products(ID),
    UNIQUE INDEX (ID_Order, ID_Product)
);

CREATE TABLE IF NOT EXISTS News_Categories (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    Name VARCHAR(255) NOT NULL UNIQUE,
    Status TINYINT(1) NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS News (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    Category_ID INT(11) NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Create_Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Image VARCHAR(255) NOT NULL,
    More_Image TEXT NULL,
    Content TEXT NOT NULL,
    Status TINYINT(1) NOT NULL DEFAULT 1,
    FOREIGN KEY (Category_ID) REFERENCES News_Categories(ID)
);

CREATE TABLE IF NOT EXISTS Comments_News (
    ID INT(11) PRIMARY KEY AUTO_INCREMENT,
    User_ID INT(11) NOT NULL,
    News_ID INT(11) NOT NULL,
    Sent_Date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    Comment TEXT NOT NULL,
    Status TINYINT(1) NOT NULL DEFAULT 1,
    FOREIGN KEY (User_ID) REFERENCES Users(ID),
    FOREIGN KEY (News_ID) REFERENCES News(ID)
);
